var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,h,m){g!=Array.prototype&&g!=Object.prototype&&(g[h]=m.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var g=0;return function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+g++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var h=0;return $jscomp.iteratorPrototype(function(){return h<g.length?{done:!1,value:g[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();var h=g[Symbol.iterator];return h?h.call(g):$jscomp.arrayIterator(g)};
$jscomp.polyfill=function(g,h,m,f){if(h){m=$jscomp.global;g=g.split(".");for(f=0;f<g.length-1;f++){var k=g[f];k in m||(m[k]={});m=m[k]}g=g[g.length-1];f=m[g];h=h(f);h!=f&&null!=h&&$jscomp.defineProperty(m,g,{configurable:!0,writable:!0,value:h})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(g){function h(){this.batch_=null}function m(d){return d instanceof k?d:new k(function(a,b){a(d)})}if(g&&!$jscomp.FORCE_POLYFILL_PROMISE)return g;h.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};h.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var f=$jscomp.global.setTimeout;h.prototype.asyncExecuteFunction=function(d){f(d,
0)};h.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var a=0;a<d.length;++a){var b=d[a];delete d[a];try{b()}catch(c){this.asyncThrow_(c)}}}this.batch_=null};h.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var k=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{d(a.resolve,a.reject)}catch(b){a.reject(b)}};k.prototype.createResolveAndReject_=
function(){function d(c){return function(e){b||(b=!0,c.call(a,e))}}var a=this,b=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};k.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof k)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var a=null!=d;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};k.prototype.resolveToNonPromiseObj_=function(d){var a=
void 0;try{a=d.then}catch(b){this.reject_(b);return}"function"==typeof a?this.settleSameAsThenable_(a,d):this.fulfill_(d)};k.prototype.reject_=function(d){this.settle_(2,d)};k.prototype.fulfill_=function(d){this.settle_(1,d)};k.prototype.settle_=function(d,a){if(0!=this.state_)throw Error("Cannot settle("+d+", "+a|"): Promise already settled in state"+this.state_);this.state_=d;this.result_=a;this.executeOnSettledCallbacks_()};k.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
this.onSettledCallbacks_,a=0;a<d.length;++a)d[a].call(),d[a]=null;this.onSettledCallbacks_=null}};var p=new h;k.prototype.settleSameAsPromise_=function(d){var a=this.createResolveAndReject_();d.callWhenSettled_(a.resolve,a.reject)};k.prototype.settleSameAsThenable_=function(d,a){var b=this.createResolveAndReject_();try{d.call(a,b.resolve,b.reject)}catch(c){b.reject(c)}};k.prototype.then=function(d,a){function b(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(u){e(u)}}:b}var c,e,l=new k(function(a,
b){c=a;e=b});this.callWhenSettled_(b(d,c),b(a,e));return l};k.prototype.catch=function(d){return this.then(void 0,d)};k.prototype.callWhenSettled_=function(d,a){function b(){switch(c.state_){case 1:d(c.result_);break;case 2:a(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?p.asyncExecute(b):this.onSettledCallbacks_.push(function(){p.asyncExecute(b)})};k.resolve=m;k.reject=function(d){return new k(function(a,b){b(d)})};k.race=function(d){return new k(function(a,
b){for(var c=$jscomp.makeIterator(d),e=c.next();!e.done;e=c.next())m(e.value).callWhenSettled_(a,b)})};k.all=function(d){var a=$jscomp.makeIterator(d),b=a.next();return b.done?m([]):new k(function(c,e){function l(a){return function(b){d[a]=b;f--;0==f&&c(d)}}var d=[],f=0;do d.push(void 0),f++,m(b.value).callWhenSettled_(l(d.length-1),e),b=a.next();while(!b.done)})};return k},"es6","es3");Date.now||(Date.now=function(){return(new Date).valueOf()});
Array.prototype.map||(Array.prototype.map=function(g,h){var m,f;if(null==this)throw new TypeError(" this is null or not defined");var k=Object(this),p=k.length>>>0;if("function"!==typeof g)throw new TypeError(g+" is not a function");1<arguments.length&&(m=h);var d=Array(p);for(f=0;f<p;){if(f in k){var a=k[f];a=g.call(m,a,f,k);d[f]=a}f++}return d});
(function(){var g={localStoreSupport:function(){try{return"localStorage"in window&&null!==window.localStorage}catch(a){return!1}},sessionStoreSupport:function(){try{return"sessionStorage"in window&&null!==window.sessionStorage}catch(a){return!1}},set:function(a,b,c){if(c){var e=new Date;e.setTime(e.getTime()+864E5*c);c="; expires="+e.toGMTString()}else c="";this.sessionStoreSupport()?sessionStorage.setItem(a,b):document.cookie=a+"="+b+c+"; path=/"},get:function(a){if(this.sessionStoreSupport())return this.delFromLocal(a),
sessionStorage.getItem(a);a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var e=b[c];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return null},delFromSession:function(a){this.sessionStoreSupport()?sessionStorage.removeItem(a):this.set(a,"",-1)},delFromLocal:function(a){this.localStoreSupport()&&localStorage.removeItem(a)},setObject:function(a,b){JSON&&this.set(a,JSON.stringify(b))},getObject:function(a){if(JSON)return(a=this.get(a))&&
JSON.parse(a)}},h=function(a,b,c,e){return{id:a,type:b,provider:c,result:e}},m=function(a,b,c){switch(c){case "criteo":return Array(h(a,b,c,"not-found"));case "ID5":var e={},l=[];try{return e=JSON.parse(decodeURIComponent(a)),e.hasOwnProperty("universal_uid")&&"string"===typeof e.universal_uid&&"0"!==e.universal_uid?l.push(h(e.universal_uid,b+"-univ",c,"ok")):e.hasOwnProperty("universal_uid")&&"string"!==typeof e.universal_uid&&l.push(h("",b+"-univ",c,"exception")),e.hasOwnProperty("original_uid")&&
"string"===typeof e.original_uid&&"0"!==e.original_uid?l.push(h(e.original_uid,b+"-orig",c,"ok")):e.hasOwnProperty("original_uid")&&"string"!==typeof e.original_uid&&l.push(h("",b+"-orig",c,"exception")),l}catch(v){return Array(h("",b,c,"exception"))}case "GrowthCode":return"undefined"!==typeof a&&"undefined"!==a?Array(h(a,b.replace(/_/gi,""),c,"ok")):Array(h("",b.replace(/_/gi,""),c,"exception"));default:return"string"===typeof a?Array(h(a,b.replace(/_/gi,""),c,"ok")):Array(h("",b.replace(/_/gi,
""),c,"exception"))}},f={isDebug:function(){return/dbg=(1|true)/.test(location)},log:function(a){f.isDebug()&&"object"===typeof window.console&&"function"===typeof console.debug&&console.debug("["+(new Date).toISOString()+"] _exaudiadapex - "+a)},replaceInitialAndFinalCharsByRegex:function(a,b,c){var e=Array.isArray(a)?[]:"",l=RegExp(b,"g"),d=RegExp(c,"g");if(Array.isArray(a))for(b=0;b<a.length;b++){var f=c=a[b];if(c.match(l)||c.match(d))f=c.replace(l,"").replace(d,"");e.push(f)}else if("string"===
typeof a){if(a.match(b)||a.match(c))e=a.replace(/^[_|-]+/,"").replace(/[_|-]+$/,"")}else e=a;return e},stripBlacklistChars:function(a){try{a=a.replace(/{|}/g,"")}catch(b){}return a},replaceWordChars:function(a){a=a.replace(/'/g,"'");a=a.replace(/\u00e0/g,"&#0224;");a=a.replace(/\u00e1/g,"&#0225;");a=a.replace(/\u00e8/g,"&#0232;");a=a.replace(/\u00e9/g,"&#0233;");a=a.replace(/\u00ec/g,"&#0236;");a=a.replace(/\u00f2/g,"&#0242;");a=a.replace(/\u00f9/g,"&#0249;");a=a.replace(/\u2014/g,"&#8212;");a=a.replace(/\u2018/g,
"&#8216;");a=a.replace(/\u2019/g,"&#8217;");a=a.replace(/\u201A/g,"&#8218;");a=a.replace(/\u201C/g,"&#8220;");a=a.replace(/\u201D/g,"&#8221;");a=a.replace(/\u201E/g,"&#8222;");return a=a.replace(/\u2026/g,"&#8230;")},isFunction:function(a){return"function"===typeof a},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return JSON.stringify(a)===JSON.stringify({})},isSecureProtocol:function(){return"https:"===
document.location.protocol},getProtocol:function(){return f.isSecureProtocol()?"https:":"http:"},random:function(){return parseInt(Math.random()*Date.now())},shuffle:function(a){for(var b=a.length,c,e;0<b;)e=Math.floor(Math.random()*b),b--,c=a[b],a[b]=a[e],a[e]=c;return a},trunc:function(a,b,c){var e=a.length>b;a=e?a.substr(0,b-1):a;a=c&&e?a.substr(0,a.lastIndexOf(" ")):a;return e?a+"&hellip;":a},getMetaData:function(a){try{var b=window.top.document}catch(l){b=document}b=b.getElementsByTagName("meta");
for(var c,e=0;e<b.length;e++)if(b[e].getAttribute("property")==a||b[e].getAttribute("name")==a){c=b[e].getAttribute("content");break}return c?c:null},loadRes:function(a,b,c){var e=document.createElement("script");e.type="text/javascript";e.src=a;e.async="true";b&&(e.onreadystatechange=e.onload=function(){var a=e.readyState;b.done||a&&!/loaded|complete/.test(a)||(b.done=!0,b())},e.onerror=function(){c&&c()});a=document.getElementsByTagName("head")[0];a.firstChild?a.insertBefore(e,a.firstChild):a.appendChild(e)},
isDomReady:function(a){function b(a){for(h=1;a=c.shift();)a()}var c=[],e,d=document,f=d.documentElement,g=f.doScroll,h=/^loade|c/.test(d.readyState);d.addEventListener&&d.addEventListener("DOMContentLoaded",e=function(){d.removeEventListener("DOMContentLoaded",e,!1);b()},!1);g&&d.attachEvent("onreadystatechange",e=function(){/^c/.test(d.readyState)&&(d.detachEvent("onreadystatechange",e),b())});return a=g?function(b){self!=top?h?b():c.push(b):function(){try{f.doScroll("left")}catch(q){return setTimeout(function(){a(b)},
50)}b()}()}:function(a){h?a():c.push(a)}}(),htmlDecode:function(a){var b=document.createElement("div");b.innerHTML=a;return 0===b.childNodes.length?"":b.childNodes[0].nodeValue},checkEventValue:function(a){if(a){var b="a age_conf age_range app_name app_version article_view_level brand c campaign carrier click_level connection_type content_ext_segment conversion_level currency d device domain domain_aug e gallery_view_level gender gender_conf geo_interest hour_range i impression_level interest lat latitude lng location_country location_region longitude loyalty_level main_app main_app_version main_carrier main_connection main_device main_device_brand main_device_model main_gps_location main_latitude main_location main_location_aug main_longitude main_op_sys_sdk main_op_sys_version main_referrer op_sys_sdk op_sys_version operating_system p pageview_level payment_type placement_id price_level purchase_category quantity_level referrer sdk_device_brand sdk_device_model standard_domain standard_interest standard_location sub_interest total_quantity_level total_spent_level url user_ext_segment v video_view_level".split(" ");
a=a.split(",");for(var c=[],e=0;e<a.length;e++)if(a[e]){var d=a[e].split("_");d&&d[0]&&0<=b.indexOf(d[0])&&(d[0]="evt"+d[0]);c.push(d.join("_"))}return c.join(",")}}},k=null,p=null,d=function(){var a=this;this.P=[];this.customerId=2033;this.instance=window._exaudiadapex||[];this.isGoodIframe=!1;this.taxonomy=this.eid=this.ge=this.ag=null;this.ids=[];try{this.document=window.parent.document,this.isGoodIframe=!0}catch(e){this.document=document}var b={S:function(b){try{a.P.push(b)}catch(l){f.log("Commands.S() > "+
b+" [ERROR]: "+l)}f.log("Commands.S() > "+b+" [COMPLETED]")},E:function(b){try{b.push(!0),a.sendEvent.apply(a,b)}catch(l){f.log("Commands.E() [ERROR]: "+l)}f.log("Commands.E() [COMPLETED]")},F:function(a){try{f.isFunction(a)&&a.apply(b)}catch(l){f.log("Commands.F() [ERROR]: "+l)}f.log("Commands.F() [COMPLETED]")}},c=function(a){function b(a,b,c){var e=Number(new Date)+(b||1E3);c=c||100;var d=function(b,f){var t=a();t?b(t):Number(new Date)<e?setTimeout(d,c,b,f):f(Error("timed out for "+a+": "+arguments))};
return new Promise(d)}var c={gdpr:1,gdpr_consent:"",enableCm:!0,objName:a};this.getData=new Promise(function(a){b(function(){return"function"===typeof __tcfapi?(__tcfapi("getTCData",2,function(a,b){if(b)return!0}),!0):!1},1E3,150).then(function(){__tcfapi("getTCData",2,function(a,b){if(b)try{c.gdpr=a.gdprApplies?1:0;c.gdpr_consent=a.tcString;b=[];for(var e in a.purpose.consents)Object.prototype.hasOwnProperty.call(a.purpose.consents,e)&&b.push(a.purpose.consents[e]);c.enableCm=a.purpose.consents[4]}catch(t){}return c});
a(c);return c}).catch(function(){a(c);return c})})};this.getNavigationInfo();this.baseURL="https://tra.neodatagroup.com";this.random=f.random();this.servlet="/pv";this.checkIframe();(function(){if(a.instance.push===Array.prototype.push){for(var c=function(a){if(!f.isArray(a))return!1;var c=a.shift();c=b[c];return f.isFunction(c)?c.apply(b,a):!1},d=0,g=a.instance.length;d<g;++d)c(a.instance[d]);a.push=c}})();this.refresh=function(){(new c("_exaudiadapex")).getData.then(function(a){window[a.objName].tcfData=
a;window[a.objName].getCall();window[a.objName].cookieMatchingProcess()})};this.tcfData=null;this.start=function(){var a=new c("_exaudiadapex");this.preprocess();this.parseParams();this.autostart&&a.getData.then(function(a){window[a.objName].tcfData=a;window[a.objName].getCall();window[a.objName].cookieMatchingProcess()})};this.getUtm();this.start()};d.prototype={siteBlacklistedForCookieMatching:[],autostart:!0,isSiteInBlacklist:function(){for(var a=!1,b=location.href,c=0;c<this.siteBlacklistedForCookieMatching.length;c++)if(0<
b.indexOf(this.siteBlacklistedForCookieMatching[c])){a=!0;break}return a},preprocess:function(){for(var a in this.instance)if("Doubleclick"===this.instance[a][0]){this.preprocessDC(this.instance[a][1]);break}},preprocessDC:function(a){this.provider="Doubleclick";this.servlet="/adv";this.keyparams=[];a=a.split("&");for(var b in a){var c=a[b].split("=");this.keyparams[c[0]]=c[1]}},parseParams:function(){var a=this.P,b;for(b in a)switch(a[b][0]){case "_taxonomy":k=a[b][1];break;case "_purchase":this.purchase=
a[b][1];break;case "_customerId":this.customerId=a[b][1];break;case "_action":this.action=a[b][1];break;case "_actionType":this.actionType=a[b][1];break;case "_actionValue":this.actionValue=a[b][1];break;case "_provider":this.provider=a[b][1];break;case "_advertising":this.advertising=a[b][1];this.servlet="/adv";break;case "_segment":this.segment=a[b][1];this.servlet="/seg";break;case "_content":this.content=a[b][1];break;case "_device":this.device=a[b][1];break;case "_auction":this.auction=a[b][1];
break;case "_user":this.user=a[b][1];break;case "_trackingUrl":this.baseURL=a[b][1];this.servlet="";break;case "_track":this.tracker=a[b][1];break;case "_serv":this.serving=a[b][1];break;case "_customVar":this.customVar=a[b][1];break;case "_tagId":this.tagId=a[b][1];break;case "_adv":this.advId=a[b][1];break;case "_cm":this.cm=a[b][1];break;case "_utm":this.utm=a[b][1];break;case "_isPreview":p=a[b][1];break;case "_ids":this.ids.push(a[b][1]);break;case "_autostart":this.autostart=a[b][1]}},getUtm:function(){if(location.search&&
0<=location.search.indexOf("utm_")){for(var a=decodeURIComponent(location.search.replace("?","")).split("&"),b=[],c=0;c<a.length;c++)if(0===a[c].indexOf("utm_")){var e=encodeURIComponent(a[c].replace("utm_","").replace(/_/g,"-").replace("=","_")),d=e;e&&(d=e.split("_"),1<d.length&&(e=d[0].toLowerCase()+"_"+d[1].replace(/ /gi,"-").replace(/%20/gi,"-").replace(/%2520/gi,"-")),e=e.split("_"),d=f.replaceInitialAndFinalCharsByRegex(e,"^[_|-]+","[_|-]+$"),d=d.join("_"));b.push(d)}0<b.length&&this.sendEvent("UTM",
"",b.join(","))}},events:[],sendEventToToolbox:function(a){this.events.push(a);try{window.postMessage&&window.postMessage({command:"neodata-toolbox-scan"},window.location.origin)}catch(b){}},sendEvent:function(a,b,c,e){this.evtValue=this.evtLabel=this.evtCat="";"undefined"!==typeof a&&(this.evtCat=encodeURIComponent(a));"undefined"!==typeof b&&(this.evtLabel=encodeURIComponent(b));"undefined"!==typeof c&&(this.evtValue=encodeURIComponent(f.checkEventValue(f.stripBlacklistChars(c))));this.getEventsCall(e)},
getEventsCall:function(a){try{if("localhost"===this.document.location.host)return}catch(c){}var b=[];this.customerId&&""!=this.customerId&&(b.push("sid="+this.customerId),this.advId&&b.push("ad="+this.advId),""!==this.evtCat&&(b.push("cat="+this.evtCat),b.push("lbl="+this.evtLabel),b.push("val="+this.evtValue),b.push("ur="+this.url),b.push("re="+this.ref),b.push("rt=img"),a&&b.push("id="+a),b.push("rnd="+this.random),a=this.baseURL+"/events",a+="?"+b.join("&"),this.sendEventToToolbox({ts:new Date,
action:"event",cat:this.evtCat,lab:this.evtLabel,val:this.evtValue,url:decodeURIComponent(this.url)}),this.addPixel(a)))},getCall:function(){var a=[],b="",c="";if(this.customerId&&""!=this.customerId){a.push("sid="+this.customerId);this.action&&(a.push("ac="+this.action),this.servlet="/adv");this.actionType&&a.push("at="+this.actionType);this.actionValue&&a.push("av="+this.actionValue);a.push("rnd="+this.random);this.providerOverride?a.push("pv="+this.providerOverride):this.provider&&a.push("pv="+
this.provider);k&&(a.push("pa="+encodeURIComponent(k)),this.taxonomy=k);this.subject&&a.push("subject="+this.subject);this.tracker&&a.push("tk="+this.tracker);this.serving&&a.push("ts="+this.serving);this.advertising&&this.advertising.map(function(b){var c=encodeURIComponent(b[0]);b=encodeURIComponent(b[1]);a.push(c+"="+b)},this);this.segment&&this.segment.map(function(b){var c=encodeURIComponent(b[0]);b=encodeURIComponent(b[1]);a.push(c+"="+b)},this);this.tagId&&a.push("id="+this.tagId);this.advId&&
a.push("ad="+this.advId);if(this.customVar){var e=[];this.customVar.map(function(a){if(!(2>a.length)){var b=a[0];(a=a[1])&&"string"===typeof a&&(a=a.replace(/_/g,"-").replace(/,/g,"-"));e.push("c"+encodeURIComponent("|")+encodeURIComponent(b).toLowerCase()+"_"+encodeURIComponent(a).toLowerCase())}},this);this.cv=0<e.length?e.join(","):"";a.push("cd="+this.cv)}this.content&&this.content.map(function(e){var d=encodeURIComponent(e[0]);e=encodeURIComponent(e[1]);"ur"===d||"re"===d?("ur"===d&&(c=e),"re"===
d&&(b=e)):a.push(d+"="+e)},this);this.device&&this.device.map(function(b){var c=encodeURIComponent(b[0]);b=encodeURIComponent(b[1]);a.push(c+"="+b)},this);this.auction&&this.auction.map(function(b){var c=encodeURIComponent(b[0]);b=encodeURIComponent(b[1]);a.push(c+"="+b)},this);if(this.user){var d=this;this.user.map(function(b){var c=encodeURIComponent(b[0]);b=encodeURIComponent(b[1]);"ge"===c.toLowerCase()&&(b="m"===b.toLowerCase()||"f"===b.toLowerCase()?b:"o");d.userOverride&&d.userOverride.hasOwnProperty(c)&&
(b=d.userOverride[c]);a.push(c+"="+b);switch(c){case "ag":this.ag=b;break;case "ge":this.ge=b;break;case "eid":this.eid=b}},this)}else if(this.userOverride)for(var f in this.userOverride)a.push(f+"="+this.userOverride[f]);if(this.keyparams)for(var g in this.keyparams){f=encodeURIComponent(g);var h=encodeURIComponent(this.keyparams[g]);"ur"===f||"re"===f?("ur"===f&&(c=h),"re"===f&&(b=h)):a.push(f+"="+h)}this.purchase&&a.push("pc="+encodeURIComponent(decodeURIComponent(this.getSource(this.purchase))));
a.push("rs="+(this.width+"x"+this.height));a.push("lg="+this.lang);a.push("tz="+this.tz);""!==c&&(this.url=c);a.push("ur="+this.url);""!==b&&(this.ref=b);a.push("re="+this.ref);a.push("co="+this.color);this.isExtendedCookieMatchingEnabled()&&this.neoIdLastSyncCheck("neoLastSync")&&a.push("cb=window._exaudiadapex.setNeoIdLastSync('@@neo_user_id@@');");this.sendEventToToolbox({ts:new Date,action:"pageview",url:decodeURIComponent(this.url)});var p=[];f="";var q=[];f="";if(this.ids&&0<this.ids.length)for(g=
0;g<this.ids.length;g++)f=this.ids[g].flat(),Array.isArray(f)&&3===f.length&&m(f[2],f[1],f[0]).forEach(function(a){var b=[];"not-found"!==a.result&&"exception"!==a.result?(b.push(a.id),b.push(a.type),b.push(a.provider),p.push(b.join(";"))):q.push(a.result+"_"+a.type.replaceAll(/_,/,"-")+"-"+a.provider.replaceAll(/_,/,"-"))});f=q.join(",");""!==f&&((new Image).src=this.baseURL+"/events?sid=999&cat=adapex-ids&lbl=&val="+f+"&ur="+this.url+"&re="+this.ref+"&rt=img&rnd="+this.random);f=p.join(",");""!==
f&&a.push("ids="+f);f=this.baseURL+this.servlet;null!==this.tcfData&&""!==this.tcfData.gdpr_consent&&a.push("gdpr="+this.tcfData.gdpr+"&gdpr_consent="+this.tcfData.gdpr_consent);this.cookieMatchingLastSyncCheck("neoLastSync_PB","Piggyback")?(a.push("pbs=true"),this.setCookieMatchingLastSync("neoLastSync_PB",(new Date).getTime())):a.push("pbs=false");f+="?"+a.join("&");this.call(f)}},call:function(a){try{if("localhost"===this.document.location.host)return}catch(c){}if(p)f.log("RTT.call [SKIPPED] - Preview Mode");
else{var b=document.createElement("script");b.type="text/javascript";b.src=a;b.async=!0;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}},cookieMatchingLastSyncCheck:function(a,b){a=g.get(a);if(!a)return f.log("SYNC - "+b+" - No lastSync stored [CALLED]"),!0;try{var c=(new Date).getTime()-a,e=864E5<c;a=parseInt(a);if(e)return f.log("SYNC - "+b+" - ELAPSED>MAX ("+c+">86400000) - [CALLED]"),!0;f.log("SYNC - "+b+" - ELAPSED>MAX ("+c+">86400000) - [SKIPPED]");return!1}catch(l){if(!a)return f.log("SYNC - "+
b+" - Error: "+l+" [CALLED]"),!0}},neoIdLastSyncCheck:function(a){a=JSON.parse(g.get(a));if(!a)return f.log("SYNC - neoId - No lastSync stored [CALLED]"),!0;try{var b=parseInt(a.ts);var c=(new Date).getTime()-b;if(864E5<c)return f.log("SYNC - neoId - ELAPSED>MAX ("+c+">86400000) - [CALLED]"),!0;f.log("SYNC - neoId - ELAPSED>MAX ("+c+">86400000) - [SKIPPED]");return!1}catch(e){if(!a)return f.log("SYNC - neoId - Error: "+e+" [CALLED]"),!0}},setNeoIdLastSync:function(a){var b=JSON.stringify({id:a,ts:(new Date).getTime()});
g.set("neoLastSync",b);this.neodataId=a},isExtendedCookieMatchingEnabled:function(){return!1},setCookieMatchingLastSync:function(a,b){g.set(a,b)},cookieMatching:function(a){a=a?a:this.provider;var b=f.getProtocol(),c=!1,e="neoLastSync_"+a;if(this.cookieMatchingLastSyncCheck(e,a)&&(null===this.tcfData||this.tcfData.enableCm)){switch(a){case "ADFORM":var d=b+"//dmp.adform.net/serving/cookie/match?party=1056&rt=img&rnd="+this.random;break;case "APPNEXUS":d="https://secure.adnxs.com/getuid?https://tracker.neodatagroup.com/cm?sid=1&pv=APN&eid=$UID&rt=img&rnd="+
this.random;break;case "DBM":d="https://cm.g.doubleclick.net/pixel?google_nid=neodata_dmp&google_cm&pv=dbm&sid=1&rt=img&rnd="+this.random;break;case "MEDIAMATH":var g=b+"//pixel.mathtag.com/sync/js?sync=auto&mt_exid=10082&exsync="+encodeURIComponent("https://tra.neodatagroup.com/cm?sid=1&pv=MEDIAMATH&eid=[MM_UUID]&rt=img&rnd="+this.random);break;case "TDD":d="https://match.adsrvr.org/track/cmf/generic?ttd_pid=neodata&ttd_tpi=1";break;case "AMAZON":this.neodataId&&(b="https://aax-eu.amazon-adsystem.com/s/dcm?pid=d0592a87-ff14-499d-9eda-8641b59e11c0&id="+
this.neodataId,d="https://tracker.neodatagroup.com/cm?eid="+this.neodataId+"&pv=AMAZON&sid=1&rd=",d+=encodeURIComponent(b));break;case "AUDIENCERATE":d="https://a.audrte.com/get?p=M1399668148&r="+encodeURIComponent(b+"//tracker.neodatagroup.com/cm?sid=1&pv=AUDIENCERATE&rt=img&rnd="+this.random+"&eid=$UID");break;case "SMARTCLIP":g="https://ad.sxp.smartclip.net/ads?plc=113750&consent=${GDPR_CONSENT_450}&rnd="+this.random;this._tcfElem.gdpr_consent&&"undefined"!==typeof this._tcfElem.gdpr_consent&&
(g=g.replace("${GDPR_CONSENT_450}",this._tcfElem.gdpr_consent));break;case "WEBORAMA":d="https://tracker.neodatagroup.com/cm?eid={WEBO_CID}&pv=weborama&sid=1&rnd="+this.random,d="https://redirect.frontend.weborama.fr/redirect/standard?url="+encodeURIComponent(d)}d&&(this.addPixel(d),c=!0);g&&(this.call(g),c=!0);c&&(this.setCookieMatchingLastSync(e,(new Date).getTime()),f.log("SYNC - "+a+" - [COMPLETED]"))}},cookieMatchingProcess:function(){if(this.cm&&0<this.cm.length)for(var a=this.cm.split(","),
b=0;b<a.length;b++)this.cookieMatching(a[b]);else this.cookieMatching("DBM")},addPixel:function(a){try{(new Image).src=a}catch(b){}},getSource:function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=isNaN(c)?'"'+c+'":':"";switch(typeof a[c]){case "object":d=f.isArray(a[c])?d+("["+this.getSource(a[c]).replace("{{","{").replace("}}","}")+"]"):d+this.getSource(a[c]);break;case "string":d+='"'+a[c]+'"';break;default:d+='"'+a[c]+'"'}b.push(d)}return"{"+b.join()+"}"},parseOgUrl:function(){for(var a=
this.document.getElementsByTagName("meta"),b=0;b<a.length;b++)if("og:url"===a[b].getAttribute("property"))return a[b].getAttribute("content");return null},parseCanonicalUrl:function(){for(var a=this.document.getElementsByTagName("link"),b=0;b<a.length;b++)if("canonical"===a[b].getAttribute("rel"))return a[b].getAttribute("href");return null},isValidUrl:function(a){try{var b=new URL(a)}catch(c){return!1}return"http:"===b.protocol||"https:"===b.protocol},getProtocol:function(a){return(new URL(a)).protocol},
getUrl:function(){var a="",b=null;this.isValidUrl(this.document.URL)&&(a=this.document.URL,b=this.getProtocol(a));var c=this.parseOgUrl();c&&this.isValidUrl(c)?(a=this.getProtocol(c),b&&a!==b&&(c=c.replace(a,b)),a=""+c):(c=this.parseCanonicalUrl())&&this.isValidUrl(c)&&(a=this.getProtocol(c),b&&a!==b&&(c=c.replace(a,b)),a=""+c);return encodeURIComponent(a)},getNavigationInfo:function(){this.url=this.getUrl();var a="";this.document.referrer&&(a=encodeURIComponent(this.document.referrer));this.ref=
a="null"===a||"unknown"===a||"undefined"===a?"":encodeURIComponent(a);a=""+navigator.language;"undefined"===a&&(a=navigator.browserLanguage);"undefined"===a&&(a="");this.lang=a;a="Netscape"!==navigator.appName?screen.colorDepth:screen.pixelDepth;"undefined"===a&&(a="");this.color=a;a=""+screen.width;"undefined"===a&&(a="");this.width=a;a=""+screen.height;"undefined"===a&&(a="");this.height=a;a=(new Date).getTimezoneOffset();"undefined"===a&&(a="");this.tz=a},checkIframe:function(){window===window.top||
this.isGoodIframe||(this.url=this.ref,this.ref="")},version:"1.1.10"};window._exaudiadapex&&void 0!==window._exaudiadapex.length?(window._exaudiadapex=new d,window._neodataTags=window._neodataTags||[],window._neodataTags.push(window._exaudiadapex)):window._exaudiadapex.autostart&&window._exaudiadapex.start()})();
(function(){var g=function(g){this.instance=window._neoJsPiggybackHandler;this.func=g;""!=this.func&&this.parseParams()};g.prototype={parseParams:function(){for(var g in this.func)"img"==this.func[g].type&&this.createImg(this.func[g].url),"js"==this.func[g].type&&this.createScript(this.func[g].url)},createImg:function(g){var h=document.getElementsByTagName("body").item(0),f=document.createElement("img");f.style.width="1px";f.style.height="1px";f.src=g;h.appendChild(f)},createScript:function(g){var h=
document.getElementsByTagName("body").item(0),f=document.createElement("script");f.setAttribute("type","text/javascript");f.src=g;h.appendChild(f)}};window._neoJsPiggybackHandler=g})();
